### ISSUE TITLE
One thing to add in Readme

### ISSUE THREAD

**Issue by wazowski78** [yTakkar/Instagram-clone#1]
Hi,
I have found your project, and I am finding it very interesting. One thing you should add to your read.me file is recommend to use Atom for MAC users. It is free and very helpful with your instructions.

**Comment by yTakkar** [comment]
Well when I started this project, I never thought of open-sourcing with github. So I didn't cared about readme or something..
Now I am trying to develop the same app but without PHP. And it will be a MERN app so it will contain more instructions on README

**Comment by yTakkar** [comment]
I am a windows user and whole app is developed on Atom. But currently loving vscode
