### ISSUE TITLE
Great work!!

### ISSUE THREAD

**Issue by Langdaa** [yTakkar/Instagram-clone#11]
Awesome project for beginners. Website looks so beautiful & it perhaps contains more features than original Instagram website.
Following you for your latest projects.
Best of luck for converting this Instagram-clone into a MERN app with NodeJS & Go on backend. 
I just read you're 18 only. Wooooooo!!

**Comment by Aamirr** [comment]
Yeah project is aweome and yes he is 18 'coz I know him!!

**Comment by yTakkar** [comment]
Thnx @Langdaa and @Aamirr !!
