### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by sadlil** [yTakkar/Instagram-clone#13]
Your project is missing LICENCE.

From [`opensource.org`](https://opensource.org):
> **What is a "permissive" Open Source license?**
A "permissive" license is simply a non-copyleft open source license — one that guarantees the freedoms to use, modify, and redistribute, but that permits proprietary derivative works. See the copyleft entry for more information.

> **Is SOME PROGRAM Open Source?**
Only if it uses one of the approved licenses, and releases appropriate software.

> **Can I call my program "Open Source" even if I don't use an approved license?**
Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people. This is not merely a theoretical concern — we have seen this confusion happen in the past, and it's part of the reason we have a formal license approval process. See also our page on license proliferation for why this is a problem.

Read More 
  1. [opensource.org](https://opensource.org/licenses)
  2. [opensource.guide](https://opensource.guide/legal/)

**Comment by yTakkar** [comment]
Which license should I add then, can you suggest me?
I have no knowledge of licensing.

**Comment by sadlil** [comment]
MIT, Apache 2.0, and GPLv3 are the most popular open source licenses, but there are other options to choose from.
My personal favourite is MIT, much simpler - non professional licence.

**Comment by yTakkar** [comment]
Should I use MIT then?

**Comment by sadlil** [comment]
So you decided not to have a licence?

**Comment by yTakkar** [comment]
No I'll be adding MIT license!

**Comment by sadlil** [comment]
That's a good news. Thank you.

**Comment by yTakkar** [comment]
Thnx to you bhai!!
