### ISSUE TITLE
My eyes are bleeding

### ISSUE THREAD

**Issue by cawa87** [yTakkar/Instagram-clone#15]
Dude, please read the http://www.php-fig.org/ and about modern php applications.

**Comment by yTakkar** [comment]
I know project is not written in modern PHP, actually it was written when I was newbie to PHP.
And I'm not a fan of PHP so I'm trying to convert into a MERN app with NodeJS & Go on the backend!!

**Comment by wazowski78** [comment]
@yTakkar you don't have to apologize to anyone, this is a great job, @CawaKharkov can evaluate tones of repositories on GitHub, and can find a lot of discontinued projects, but even if you are not a PHP lover, and you are not using any framework like laravel or symphony, li @CawaKharkov does, this project is a gem for me and other programmers. Great job friend!!
