### ISSUE TITLE
Not working. Help.

### ISSUE THREAD

**Issue by sp1red** [yTakkar/Instagram-clone#16]
I uploaded everything to my web server and also uploaded the instagram.sql to PhpMyAdmin, but when I go to the website for my web server that I uploaded these files to, it is just a white screen. I don't know if I did something wrong or not.? Please help. Thank you.

**Comment by yTakkar** [comment]
If all the steps are followed well, then it works

**Comment by yTakkar** [comment]
All the followed all the steps for you & it worked!!
Also make sure you have latest version of PHP.
Also go through some other [issues](https://github.com/yTakkar/Instagram-clone/issues?q=is%3Aissue+is%3Aclosed) to get some help!!

**Comment by yTakkar** [comment]
or send me a screenshot of errors!!

**Comment by ThejeswarReddy** [comment]
be sure address the directories correctly, it must be a addressing issue..
