### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by pro100it** [yTakkar/Instagram-clone#17]
The script is good! There is one flaw or something I do not do the right thing. Does not work when you leave the site. White screen, no redirect. If you go back to the page, go to your profile. It is impossible to get out!

And.... you plan to make the script multilingual?

**Comment by yTakkar** [comment]
Impossible to get out?? You mean there's a problem with logout??
If there's a problem with logout, I must assure you that it's working!!

**Comment by pro100it** [comment]
I bet on hosting, tried different versions of php in any browser is not working. Why might that be? what did I do wrong while installing?

**Comment by yTakkar** [comment]
I think it could be a problem of installation!!

**Comment by pro100it** [comment]
Ok! I'll try to reinstall
