### ISSUE TITLE
Not an issue. It

### ISSUE THREAD

**Issue by MarcAnthonyPhotography** [yTakkar/Instagram-clone#18]
Any thoughts on implementing an API that would allow iOS developers, like myself, to offer an iPhone app to work with this? And, would you be able implement Amazon S3 bucket hosting for the files instead of on the users own hosting?

**Comment by yTakkar** [comment]
I don't have any plan to implement anything you just mentioned, but if you want you could implement for yourself!!
I open-sourced it so anyone can take this as a base project and then customize according to their needs!!
