### ISSUE TITLE
not able to signup and signin

### ISSUE THREAD

**Issue by deepakindwar** [yTakkar/Instagram-clone#20]
sir i am running your instagram clone in local server. but when i am trying to do signup then a notification comes and not able to signup. i am also trying to login with username-takkar pass-takkar but not logging. please solve my issue. and if possible then send me the codes after solving issue. i will be thankful to you.
here i have attached the problem pic.thanks.

![ instagram issue pic ](https://user-images.githubusercontent.com/31152441/29484449-931682fc-84dc-11e7-956d-7e5891046626.jpg)

**Comment by yTakkar** [comment]
That's a PDO connection problem in your `config/class/needy_class.php`.
I'm 18, so don't call me sir, just faiyaz!!

**Comment by yTakkar** [comment]
If instructions are followed well, then it must work.
I followed the instructions again for you and it worked.
