### ISSUE TITLE
.Php error

### ISSUE THREAD

**Issue by aslantassmt** [yTakkar/Instagram-clone#22]
For example when I try to login I have to write .php. Like this;
I installed files in "public_html" so I write " " to DIR.
http://prntscr.com/gc1n8x
http://prntscr.com/gc1nk8

**Comment by aslantassmt** [comment]
I write this things on .htaccess file. The problem partly solved but this time some link are not working.
For example; 

https://playerally.com/mvp/profile/Serius?ask=bookmarks
https://playerally.com/mvp/profile/Serius?ask=favourites
https://playerally.com/mvp/profile/Serius?ask=groups

> RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^\.]+)$ $1.php [NC,L]

**Comment by aslantassmt** [comment]
I fixed my problem myself :D
Just add this to .htaccess.

> RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
>RewriteRule ^([a-zA-Z0-9_]+)$ $1.php [QSA,NC,L]
>RewriteRule ^profile/([a-zA-Z0-9._@\-]+)$ profile.php?u=$1 [QSA,NC,L]
RewriteRule ^profile/ profile.php [QSA,NC,L]
>RewriteRule ^groups/([0-9]+)$ groups.php?grp=$1 [QSA,NC,L]
RewriteRule ^groups groups.php [QSA,NC,L]
>RewriteRule ^view_post/([a-zA-Z0-9_]+)$ view_post.php?post=$1 [QSA,NC,L]
>RewriteRule ^([^\.]+)$ $1.php [NC,L]
>ErrorDocument 404/mvp/404.php

**Comment by aslantassmt** [comment]
Can you share your .htaccess file? There is a problem with other things. @yTakkar

**Comment by yTakkar** [comment]
It's already in the repo!!
