### ISSUE TITLE
Mail and Post List

### ISSUE THREAD

**Issue by aslantassmt** [yTakkar/Instagram-clone#23]
When I posted a text I am clicking to profile to view it but loading screen always turning. And it isn't viewed. There is no problem on picture etc. I tried to reinstall and change database.

The other problem is sending e-mail I typed correctly my gmail account. But there aren't any e-mail.(Verification, password recovery etc.) When I click Resend Activation button. E-mail sending is failed.

I hope you will help me.
Thank you.

**Comment by aslantassmt** [comment]
You can check. http://playerally.com/test/

**Comment by yTakkar** [comment]
First of all, you're allowing logged out user to post.
First solve this issue, then I'm sure it will work properly!!

**Comment by aslantassmt** [comment]
No man, I solve the problem which you talking about but problems already same. It is not about me I think. @yTakkar

**Comment by yTakkar** [comment]
And for email, you have to
