### ISSUE TITLE
Not opening extention link

### ISSUE THREAD

**Issue by brojee** [yTakkar/Instagram-clone#26]
I have uploaded script and changed everything which was told by your installation process.

But the problem is any page with its extention isnt opening ...
For example i click login button the url goes to (www.mysite.com/login) , it should go to (www.mysite.com/login.php).

So by this problem not any single page is opening

**Comment by yTakkar** [comment]
You don't have to add .php at the end of any app URL, it's configured in .htaccess file.
If you have to access any link, it will be opened without extension name!!

**Comment by brojee** [comment]
But my ftp dosent uploads .htaccess file

**Comment by brojee** [comment]
I have uploaded .htaccess file , extention error is okay now but login and signup things are stopped . Every setting is okay but why this now ?

**Comment by yTakkar** [comment]
Then find a way, 'coz the app won't work expectedly with .htacces file, let it be profile page, hashtag page, messages page or group page!!

**Comment by brojee** [comment]
Sir .htaccess file has been uploaded but now login and signup isnt working before that it was working

**Comment by yTakkar** [comment]
Have a look on this link, this might solve it.
https://github.com/yTakkar/Instagram-clone#loginsignup-error

**Comment by brojee** [comment]
Just checked that but login was working before i uploaded .htaccess file

**Comment by brojee** [comment]
Fatal Error comes while signup .... how to solve that ?

**Comment by brojee** [comment]
Fatal error comming on config/login-class.php line 74

Please tell me whats this

**Comment by yTakkar** [comment]
You should have the latest version of PHP.
https://github.com/yTakkar/Instagram-clone/issues/3#issuecomment-304709493

**Comment by brojee** [comment]
Yes i have latest version sir

**Comment by brojee** [comment]
Before uploading .htaccess file everything was okay except extention problem , but now signup error is coming

**Comment by wazowski78** [comment]
Have you checked the error logs of your server????
Please, share the files with us and it is possible we can help. Otherwise debug yourself the issue or give us more information. Repeating the same thing again and again will not solve the problem. Be positive and we may can help you. I had a lot of issues with my server configuration, but I could solve them my self, but if you need help just share as much information as you can.

**Comment by brojee** [comment]
Add me on insta (@mth.official) or email me on (brojeeoff@gmail.com) i can provide you my cpanel details so that you can easy check whats the problem

**Comment by brojee** [comment]
Any one of you please make my files okay ? But need trusted one

**Comment by brojee** [comment]
Which file you need so that i can share

**Comment by brojee** [comment]
yTakkar can you please install on my server i can provide details ....

**Comment by yTakkar** [comment]
Sorry, you'd have to do it by yourself!!

**Comment by brojee** [comment]
Dear , but please tell me how can i solve the signup thing ... other than that every thing is working

**Comment by yTakkar** [comment]
Go to signup page, fill every details (dummy details), open console, take screenshots & send it!!

**Comment by brojee** [comment]
This is happening...
![screenshot_20170906-121757](https://user-images.githubusercontent.com/31335894/30099063-e60ea212-92fd-11e7-8645-a74ef961ea5b.jpg)

**Comment by yTakkar** [comment]
Maybe @wazowski78 can help because he too had a problem with password_hash() function. But he solved in the end!!

**Comment by wazowski78** [comment]
Hi @yTakkar and @brojee 
my problem was related to the PHP version running in my server, so you have to check yours. Have a look to your phpinfo, make a screenshot and share here, so we can check it.

**Comment by brojee** [comment]
Done , updated php version and every thing is okay

**Comment by brojee** [comment]
What this now sir .....
![screenshot_20170909-113142](https://user-images.githubusercontent.com/31335894/30237785-8cbebb3c-9552-11e7-913d-a45c328c8552.png)

**Comment by yTakkar** [comment]
@brojee 
It's a typo error.
Go ahead and change `text_Post` table to `text_post`.
I'll fix this typo & commit it!!
https://github.com/yTakkar/Instagram-clone/commit/9244759bd6eb4add9a19ec257cdd31544a3884a4

**Comment by brojee** [comment]
It is text_post like this already

**Comment by brojee** [comment]
And login page stayes idol after putting in information to login it does not login actually

**Comment by yTakkar** [comment]
well, you have/had lots of problem with this project

**Comment by yTakkar** [comment]
Definitely it's a typo error.
Or text_post doesn't exist!!
Read the error!!

**Comment by brojee** [comment]
Can you make this project 100% error free and add more features ... i am ready to invest $1000 on this

**Comment by yTakkar** [comment]
Actually I no longer work on this project, as working on this project doesn't excite me now!!

**Comment by yTakkar** [comment]
Also code is not up to date.
Project is not ready for production, only for learning & fun purposes!!

**Comment by wazowski78** [comment]
@brojee contact me at m.wazowski.00@gmail.com. We can talk about your problems and if you want talk about your project, right?

**Comment by wazowski78** [comment]
I think @yTakkar can close this issue.

**Comment by brojee** [comment]
Yes sure i will email you as soon as possible ... basically i was finding a developer to develop a proper new social network ... but beside that i am ready to invest $1000 on this one too to make it perfect
