### ISSUE TITLE
MySQL issue with variable name

### ISSUE THREAD

**Issue by wazowski78** [yTakkar/Instagram-clone#27]
I have found this issue when calling this SQL request:
`SELECT MAX(login_id) AS get FROM login WHERE user_id = :id LIMIT 1`

I have found that 'get' is a reserved instance, so I am getting errors using it, I have changed it for 'myget' in this way:
`SELECT MAX(login_id) AS myget FROM login WHERE user_id = :id LIMIT 1`
and changed this row as well:
`$login = $row->myget;`

It is possible someone are getting this error too.

**Comment by yTakkar** [comment]
Send a PR!!

**Comment by yTakkar** [comment]
And 1 more guy had this problem!!

**Comment by yTakkar** [comment]
OK. Solved it!!
