### ISSUE TITLE
Not an Issue, Just Question

### ISSUE THREAD

**Issue by BlackBeardo** [yTakkar/Instagram-clone#28]
Hello @yTakkar . 

This is awesome thing you created so far.

I installed it, got some bugs in my mac but I solved it.

I really appreciate this work.

I have a question:
"Can we have any kind of Admin Control or panel where we can manage thing from behind the scenes, like, admin email, pass, logo, site name, titles."

I want to make friend's personal community site. I have very large friend circle. really big.

**Comment by yTakkar** [comment]
First of all, this project is just a base project. Anyone can customize it according to their needs.
If you wanna create a Admin panel, go ahead and create it!!
I no longer work on this project, so I couldn't make it!!

**Comment by BlackBeardo** [comment]
I am planning to make it. but I am codeigniter developer. so I have to make admin very separate from your code. 

Thanks.

**Comment by yTakkar** [comment]
ok
