### ISSUE TITLE
Post issue

### ISSUE THREAD

**Issue by wazowski78** [yTakkar/Instagram-clone#4]
Hi again,
I am getting problems with posts, I can get my post shown in the home or profile page.

I ave tested that all the information is stored in the database, but it seems that it is not posed in the web. Other thing, when I send text_post from home page, it seems to be sent but it is not shown in the timeline. But when I try to post an image the post dialog stucks and is not closing the dialog, but the image and the text is stored in the database.

Any tip? Can you tell me the flow of posting, and the flow of showing them?

**Comment by yTakkar** [comment]
Well I never got that error, so i have no idea!!

**Comment by wazowski78** [comment]
For example in user profile images are loading fine, but posts are not loading.The URL al the call is 
`/main/profile/diego?ask=posts`
I only get a spinner loading but the posts are not loading. Can you tell me the flow of the show posts process in order to help me to debug it please?

**Comment by wazowski78** [comment]
Well!! I have found an issue with the code and the database:

`Wed May 31 09:41:43.001611 2017] [:error] [pid 3191] [client 148.56.33.61:51579] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pyinstagram.text_Post' doesn't exist' in /var/www/html/main/config/class/post.class.php:450\nStack trace:\n#0 /var/www/html/main/config/class/post.class.php(450): PDOStatement->execute(Array)\n#1 /var/www/html/main/config/class/post.class.php(663): post->getDifferentPost('text', '7', '14')\n#2 /var/www/html/main/ajaxify/home/home.php(56): post->getHomePost('direct', 'nolimit', '0')\n#3 /var/www/html/main/index.php(40): include_once('/var/www/html/m...')\n#4 {main}\n  thrown in /var/www/html/main/config/class/post.class.php on line 450`

I am debugging now, so I hope to find something else.

**Comment by wazowski78** [comment]
Done! There is an error between database and post PDO fetch objects.

**Comment by evan9523** [comment]
Can you please help me get my posts on the feed ? Please
