### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by WebCrew** [yTakkar/Instagram-clone#41]
First of all - You  have done **a great job**, I like the script.

- Are You planing to develop a **Installer Script** for the system?

- Will You create a **Admin Section** for project/site owners?

- At the moment the only way to manage site users (delete or add some) **is by manipulating the sql database table, right**? 

- Same **to delete posts, content** etc.?

I like what You did so far, **it is looking amacingly good**, but it would be cool if the clone would become a bit more of a real CMS - so more content management and setting options for site or project  admins.

THX a lot ;)

**Comment by yTakkar** [comment]
I am not planning anything for the project.
This is just a base project, so anyone can add features according to their needs!!

**Comment by WebCrew** [comment]
Ok thank You very much for the info. You have done a very good job with it and I also like the style and design a lot - to sad that You do not plan further updates.

I wish You a nice day,
kind regards from Germany,

Andi
