### ISSUE TITLE
getting error SQLSTATE[42000] [1203] User ********* already has more than 'max_user_connections' active connections on hostgator

### ISSUE THREAD

**Issue by tannyboy21** [yTakkar/Instagram-clone#43]

**Comment by tannyboy21** [comment]
this error was solved but Oops, no such member found! on profile page

**Comment by gntmind** [comment]
how did you solved 42000 error let me know

**Comment by Runixuz** [comment]
hello 
login page open eroor

**Comment by yTakkar** [comment]
Acutally, I've stopped maintaining this project, why not you use another version of this project which is much faster, reactive and a single-page application.
[Another Version](https://github.com/yTakkar/React-Instagram-Clone-2.0)
