### ISSUE TITLE
When posting, some HTML is visible

### ISSUE THREAD

**Issue by ROMTypo** [yTakkar/Instagram-clone#44]
![screen shot 2017-12-17 at 8 58 32 am](https://user-images.githubusercontent.com/18755147/34081348-8a060de2-e308-11e7-807c-92b6f554322b.png)

**Comment by marcosemg** [comment]
I have the same problem. And the search does not work.

**Comment by yTakkar** [comment]
Acutally, I've stopped maintaining this project, why not you use another version of this project which is much faster, reactive and a single-page application.
[Another Version](https://github.com/yTakkar/React-Instagram-Clone-2.0)
