### ISSUE TITLE
Where is the admin backend? 

### ISSUE THREAD

**Issue by cod3box** [yTakkar/Instagram-clone#46]
Hi, this is more a question not an issue. Is there an admin backend page or can i login as admin? if yes what is the admin username and password ? 
I installed the script and i 'm in the welcome page. How can i set an admin user and password? 

Thanks

**Comment by yTakkar** [comment]
There's no admin system

**Comment by yTakkar** [comment]
I am creating a MERN version of this project which will have the admin system
