### ISSUE TITLE
when trying to open someone else profile other than logged in user it shows error

### ISSUE THREAD

**Issue by gntmind** [yTakkar/Instagram-clone#47]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'get FROM login WHERE user_id = '139' LIMIT 1' at line 1' in

**Comment by yTakkar** [comment]
Acutally, I've stopped maintaining this project, why not you use another version of this project which is much faster, reactive and a single-page application.
[Another Version](https://github.com/yTakkar/React-Instagram-Clone-2.0)
