### ISSUE TITLE
where is admin panel

### ISSUE THREAD

**Issue by lablnet** [yTakkar/Instagram-clone#5]

**Comment by yTakkar** [comment]
There's no admin panel!

**Comment by ThejeswarReddy** [comment]
How about making one?

**Comment by yTakkar** [comment]
I'm busy with some other projects, so I won't be able to work on admin panel.
If you want, you can make one and use it according to your needs!!

**Comment by lablnet** [comment]
Can i send you poll request
On Wednesday, August 16, 2017, Faiyaz Shaikh <notifications@github.com>
wrote:
> I'm busy with some other projects, so I won't be able to work on admin
panel.
> If you want, you can make it one and use it according to your needs!!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/IuJx_2ZqW-R8n-KpgwwHck1lRt5Ch6x1-K58Sy4O5WbXx8tANVtqx4cZPu3tTZHQNzFaszeGcYL0b-pNYdnrZ_W6K21LqN76oaTuFTU7xKP-bKeYAmvWfWJVNspEwVYN5feFVt16Eo2t7urGnel_RkhrB4fqkw=s0-d-e1-ft#https://github.com/notifications/beacon/AaeM2QEEfC8awNJK6yZWisvSEXICG7QXks5sYfj2gaJpZM4N2QSJ.gif>
