### ISSUE TITLE
The requested resource ~/welcome was not found on this server.

### ISSUE THREAD

**Issue by tenaciousd93** [yTakkar/Instagram-clone#50]
I cloned you git repository and edit files as reported in "Own the Project" of readme file but when go to code directory and serve the code with php command `$ php56 -S localhost:8080` (or `$ php -S localhost:8080` for php7) I can't see welcome page, I see a php 404 error:
`The requested resource /path/to/project/Instagram-clone/welcome was not found on this server.`
The path to welcome.php is correct.

In terminal, I see php serve command output:
```
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined index: id in /path/to/project/Instagram-clone/index.php on line 21
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined index: id in /path/to/project/Instagram-clone/config/class/avatar.class.php on line 13
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined offset: 0 in /path/to/project/Instagram-clone/config/class/avatar.class.php on line 15
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined index: id in /path/to/project/Instagram-clone/config/class/post.class.php on line 605
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined index: id in /path/to/project/Instagram-clone/config/class/suggestions.class.php on line 16
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined index: id in /path/to/project/Instagram-clone/config/class/hashtag.class.php on line 118
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined index: id in /path/to/project/Instagram-clone/config/class/avatar.class.php on line 13
[Mon Feb 26 21:28:54 2018] PHP Notice:  Undefined offset: 0 in /path/to/project/Instagram-clone/config/class/avatar.class.php on line 15
[Mon Feb 26 21:28:54 2018] ::1:49424 [302]: /
[Mon Feb 26 21:28:54 2018] ::1:49446 [404]: /path/to/project/Instagram-clone/welcome - No such file or directory
```
Where I am wrong?
I'm on Macbook MacOS 10.13 with php 5.6.16 or php 7.0.23.
Thanks!

**Comment by yTakkar** [comment]
Acutally, I've stopped maintaining this project, why not you use another version of this project which is much faster, reactive and a single-page application.
[Another Version](https://github.com/yTakkar/React-Instagram-Clone-2.0)

**Comment by Runixuz** [comment]
xampp install 
xampp worked

**Comment by Subhajit25Mondal** [comment]
check that all the directories are renamed properly or not ??? the index.php cannot locate the files from the directories.

Hope it will help you

**Comment by tenaciousd93** [comment]
Hello, the directory was renamed properly.
I moved to other version linked by yTakkar.
Not tried Runixuz solution.
Maybe you can reject this issue or close it.
