### ISSUE TITLE
Profile Page only works for self

### ISSUE THREAD

**Issue by sanity97** [yTakkar/Instagram-clone#51]
Hey,
I know you said you stopped working on this projekt and started multiple others but since I only have access to my webspace and no access to SSH or anything like that I am reliant on the PHP-Only version so I wanted to give it a shot by asking for your help in this.

I have the issue that profile pages only load for yourself, meaning you can see your own full profile but you cannot see anything on the profile of others, neither can you click the "expand bio" or unfollow buttons, the links just end the url in # and nothing happens after that.

http://prntscr.com/in9dgl - this is what it looks like if you access someone else's profile, everything else such as the News Feed works properly.. Maybe you got a quick fix. I didn't change anything except for the parts mentioned in the readme.

**Comment by yTakkar** [comment]
Have you checked the console for any error

**Comment by sanity97** [comment]
Yeah just CSS errors regarding browser support (moz stuff)

Checking these errors I also checked the general CSS/used HTML of the page and it just ends after the "Tags"-Button, which is weird because the template does not since you can see it on your own profile. I also made sure the profiles are non-private and/or following each other.

**Comment by sanity97** [comment]
Was an issue with the Get variable, I switched that up and now it's back to normal.
