### ISSUE TITLE
Having Issue 

### ISSUE THREAD

**Issue by adesoye0** [yTakkar/Instagram-clone#6]
This is Emperor Haqulix.. Please could you make available of those screen shots of how to go about it? Thanks

**Comment by yTakkar** [comment]
got it

**Comment by yTakkar** [comment]
![snap 2017-06-15 at 04 11 47](https://user-images.githubusercontent.com/24929880/27157910-ae1b2654-5181-11e7-8cf4-311f6a36aae7.png)

These are initial files which cloned from the repository using cmd

**Comment by adesoye0** [comment]
Okay.. Can't see the screen shots

**Comment by adesoye0** [comment]
Or can you just send all those screen shots to my email at ayoolaadesoye9@gmail.com ? Thanks!

**Comment by adesoye0** [comment]
Helloo. Please I am facing difficulties accessing  Note Cloned Code. Please can you be of help? Thanks
