### ISSUE TITLE
Unable to open links 

### ISSUE THREAD

**Issue by alsong** [yTakkar/Instagram-clone#63]
After seeing in you demo how you open lipsum.com, I tried it and it's not working. Do I have to make some changes @yTakkar i know you have stopped on the project.
i just need a favour from you on how you made it work. Thanks alot

**Comment by alsong** [comment]
http://sourceforge.net/projects/simplehtmldom/

I went and got an update and then updated the code and it works

**Comment by evan9523** [comment]
How did you do it bro ?
